export const portfolioContent = [
    {
        title: "codeRefractor",
        url: "https://andypedonti.github.io/HomeWorkWk1/",
        description: "A simple JavaScript Program using semantic HTML",
        github: "https://github.com/andypedonti/HomeWorkWk1",
        html: "html5",
        css: "",
        javascript: "",
        node: "",
        react: "",
        jquerry: "",
        mongo: "",
        mysql: "",
        bootstrap: "",
        npm: ""

    },
    {
        title: "Bootstrap CSS",
        url: "https://andypedonti.github.io/HomeWorkWk2/",
        description: "an example us using Bootstrap CSS",
        github: "https://github.com/andypedonti/HomeWorkWk2",
        html: "html5",
        css: "css3",
        javascript: "",
        node: "",
        react: "",
        jquerry: "",
        mongo: "",
        mysql: "",
        bootstrap: "bootstrap",
        npm: ""
    },
    {
        title: "passwordGenerator",
        url: "https://andypedonti.github.io/passWord/",
        description: "A Program that generates a password using JavaScript",
        github: "https://github.com/andypedonti/passWord",
        html: "",
        css: "",
        javascript: "javascript",
        node: "",
        react: "",
        jquerry: "",
        mongo: "",
        mysql: "",
        npm: ""
    },
    {
        title: "Trout Tester",
        url: "https://andypedonti.github.io/javaQuiz/",
        description: "A simple app that uses JavaScript to test your knowledge of trout",
        github: "https://github.com/andypedonti/javaQuiz",
        html: "html5",
        css: "css3",
        javascript: "javascript",
        node: "",
        react: "",
        jquerry: "",
        mongo: "",
        mysql: "",
        npm: "",
        bootstrap: ""

    },
    {
        title: "dayPlanner",
        url: "https://andypedonti.github.io/workDayPlanner/",
        description: "An app that uses JavaScript and CSS to help you plan your day",
        github: "https://github.com/andypedonti/workDayPlanner",
        html: "",
        css: "css3",
        javascript: "javascript",
        node: "",
        react: "",
        jquerry: "jquerry",
        mongo: "",
        mysql: "",
        npm: "",
        bootstrap: ""
    },
    {
        title: "weatherApp",
        url: "https://andypedonti.github.io/weatherApp/",
        description: "A weather app that uses geolocation, JavaScript, JQuery, CSS and openWeather API to give you a weather forecast",
        github: "https://github.com/andypedonti/Party-Planning-Committee",
        html: "html5",
        css: "css3",
        javascript: "javascript",
        node: "",
        react: "",
        jquery: "jquery",
        mongo: "",
        mysql: "",
        npm: "",
        bootstrap: ""
    },
    {
        title: "projectOne",
        url: "https://andypedonti.github.io/Party-Planning-Committee/",
        description: "An app using HTML, CSS, JavaScript, API, JQuerry to help you plan a meal based on what you actually have in the fridge",
        github: "https://github.com/andypedonti/Party-Planning-Committee",
        html: "html5",
        css: "",
        javascript: "javascript",
        node: "css3",
        react: "",
        jquerry: "",
        mongo: "",
        mysql: "",
        bootstrap: "",
        npm: ""
    },
    {
        title: "readmeGenerator",
        url: "https://github.com/andypedonti/pesticideRecord",
        description: "An app that uses Node.Js to create a markdown file",
        github: "https://github.com/andypedonti/pesticideRecord",
        html: "",
        css: "",
        javascript: "javascript",
        node: "nodejs_small",
        react: "",
        jquerry: "",
        mongo: "",
        mysql: "",
        bootstrap: "",
        npm: "npm"
    },
    {
        title: "teamProfileGenerator",
        url: "https://github.com/andypedonti/templateEngine",
        description: "A CLI app that utilizes tests and Node.js inquirer to create an html page.",
        github: "https://github.com/andypedonti/templateEngine",
        html: "",
        css: "",
        javascript: "javascript",
        node: "nodejs_small",
        react: "",
        jquerry: "",
        mongo: "",
        mysql: "",
        bootstrap: "",
        npm: "npm"
    },

    {
        title: "fitnessTracker",
        url: "https://lit-gorge-03085.herokuapp.com/",
        description: "This is a NoSQL database app",
        github: "https://github.com/andypedonti/fitnessTracker",
        html: "",
        css: "",
        javascript: "javascript",
        node: "",
        react: "",
        jquerry: "",
        mongo: "mongodb",
        mysql: "",
        bootstrap: "",
        npm: "npm"
    },
    {
        title: "noteTaker",
        url: "https://fathomless-scrubland-82808.herokuapp.com/",
        description: "An app that uses Express and get, put, and delete routes",
        github: "https://github.com/andypedonti/noteTaker",
        html: "",
        css: "",
        javascript: "javascript",
        node: "",
        react: "",
        jquerry: "",
        mongo: "",
        mysql: "",
        bootstrap: "",
        npm: "npm"
    },
    {
        title: "userDirectory",
        url: "https://andypedonti.github.io/goodEmployeeDir/",
        description: "This is a React.js app that searches a database",
        github: "https://github.com/andypedonti/goodEmployeeDir",
        html: "html5",
        css: "css3",
        javascript: "javascript",
        node: "",
        react: "react",
        jquerry: "",
        mongo: "",
        mysql: "",
        bootstrap: "",
        npm: "npm"
    },
];